//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchroRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class SynchroRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] responsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNum {
            get {
                return this.SerialNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNumField, value) != true)) {
                    this.SerialNumField = value;
                    this.RaisePropertyChanged("SerialNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] responses {
            get {
                return this.responsesField;
            }
            set {
                if ((object.ReferenceEquals(this.responsesField, value) != true)) {
                    this.responsesField = value;
                    this.RaisePropertyChanged("responses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class RequestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCheckResponseModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class UserCheckResponseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UserBasicInfo UserInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UserBasicInfo UserInfo {
            get {
                return this.UserInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserInfoField, value) != true)) {
                    this.UserInfoField = value;
                    this.RaisePropertyChanged("UserInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBasicInfo", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class UserBasicInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnlockClearQAResponseModel", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class UnlockClearQAResponseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.QResponse QResponseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.QResponse QResponse {
            get {
                return this.QResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.QResponseField, value) != true)) {
                    this.QResponseField = value;
                    this.RaisePropertyChanged("QResponse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QResponse", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class QResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] QsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Qs {
            get {
                return this.QsField;
            }
            set {
                if ((object.ReferenceEquals(this.QsField, value) != true)) {
                    this.QsField = value;
                    this.RaisePropertyChanged("Qs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class AuthRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustID {
            get {
                return this.CustIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustIDField, value) != true)) {
                    this.CustIDField = value;
                    this.RaisePropertyChanged("CustID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassCode {
            get {
                return this.PassCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PassCodeField, value) != true)) {
                    this.PassCodeField = value;
                    this.RaisePropertyChanged("PassCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthResponse", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class AuthResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated {
            get {
                return this.AuthenticatedField;
            }
            set {
                if ((this.AuthenticatedField.Equals(value) != true)) {
                    this.AuthenticatedField = value;
                    this.RaisePropertyChanged("Authenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateUserRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class UpdateUserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNoRequest", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class SerialNoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustID {
            get {
                return this.CustIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustIDField, value) != true)) {
                    this.CustIDField = value;
                    this.RaisePropertyChanged("CustID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialNoResponse", Namespace="http://schemas.datacontract.org/2004/07/EntrustWrapper.Model")]
    [System.SerializableAttribute()]
    public partial class SerialNoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serialno {
            get {
                return this.SerialnoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialnoField, value) != true)) {
                    this.SerialnoField = value;
                    this.RaisePropertyChanged("Serialno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TwoFactorAuthService.IAuthWrapper")]
    public interface IAuthWrapper {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/SynchronizeToken", ReplyAction="http://tempuri.org/IAuthWrapper/SynchronizeTokenResponse")]
        FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel SynchronizeToken(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SynchroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/SynchronizeToken", ReplyAction="http://tempuri.org/IAuthWrapper/SynchronizeTokenResponse")]
        System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel> SynchronizeTokenAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SynchroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UnlockUser", ReplyAction="http://tempuri.org/IAuthWrapper/UnlockUserResponse")]
        FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel UnlockUser(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UnlockUser", ReplyAction="http://tempuri.org/IAuthWrapper/UnlockUserResponse")]
        System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel> UnlockUserAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/CheckUser", ReplyAction="http://tempuri.org/IAuthWrapper/CheckUserResponse")]
        FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UserCheckResponseModel CheckUser(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/CheckUser", ReplyAction="http://tempuri.org/IAuthWrapper/CheckUserResponse")]
        System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UserCheckResponseModel> CheckUserAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UnlockUserandClearQA", ReplyAction="http://tempuri.org/IAuthWrapper/UnlockUserandClearQAResponse")]
        FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UnlockClearQAResponseModel UnlockUserandClearQA(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UnlockUserandClearQA", ReplyAction="http://tempuri.org/IAuthWrapper/UnlockUserandClearQAResponse")]
        System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UnlockClearQAResponseModel> UnlockUserandClearQAAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/AuthMethod", ReplyAction="http://tempuri.org/IAuthWrapper/AuthMethodResponse")]
        FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthResponse AuthMethod(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/AuthMethod", ReplyAction="http://tempuri.org/IAuthWrapper/AuthMethodResponse")]
        System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthResponse> AuthMethodAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UpdateUserDetails", ReplyAction="http://tempuri.org/IAuthWrapper/UpdateUserDetailsResponse")]
        FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel UpdateUserDetails(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/UpdateUserDetails", ReplyAction="http://tempuri.org/IAuthWrapper/UpdateUserDetailsResponse")]
        System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel> UpdateUserDetailsAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/GetTokenSerial", ReplyAction="http://tempuri.org/IAuthWrapper/GetTokenSerialResponse")]
        FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoResponse GetTokenSerial(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthWrapper/GetTokenSerial", ReplyAction="http://tempuri.org/IAuthWrapper/GetTokenSerialResponse")]
        System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoResponse> GetTokenSerialAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthWrapperChannel : FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.IAuthWrapper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthWrapperClient : System.ServiceModel.ClientBase<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.IAuthWrapper>, FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.IAuthWrapper {
        
        public AuthWrapperClient() {
        }
        
        public AuthWrapperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthWrapperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWrapperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthWrapperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel SynchronizeToken(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SynchroRequest request) {
            return base.Channel.SynchronizeToken(request);
        }
        
        public System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel> SynchronizeTokenAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SynchroRequest request) {
            return base.Channel.SynchronizeTokenAsync(request);
        }
        
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel UnlockUser(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request) {
            return base.Channel.UnlockUser(request);
        }
        
        public System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel> UnlockUserAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request) {
            return base.Channel.UnlockUserAsync(request);
        }
        
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UserCheckResponseModel CheckUser(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request) {
            return base.Channel.CheckUser(request);
        }
        
        public System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UserCheckResponseModel> CheckUserAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request) {
            return base.Channel.CheckUserAsync(request);
        }
        
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UnlockClearQAResponseModel UnlockUserandClearQA(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request) {
            return base.Channel.UnlockUserandClearQA(request);
        }
        
        public System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UnlockClearQAResponseModel> UnlockUserandClearQAAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.RequestModel request) {
            return base.Channel.UnlockUserandClearQAAsync(request);
        }
        
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthResponse AuthMethod(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthRequest request) {
            return base.Channel.AuthMethod(request);
        }
        
        public System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthResponse> AuthMethodAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.AuthRequest request) {
            return base.Channel.AuthMethodAsync(request);
        }
        
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel UpdateUserDetails(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UpdateUserRequest request) {
            return base.Channel.UpdateUserDetails(request);
        }
        
        public System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.ResponseModel> UpdateUserDetailsAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.UpdateUserRequest request) {
            return base.Channel.UpdateUserDetailsAsync(request);
        }
        
        public FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoResponse GetTokenSerial(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoRequest request) {
            return base.Channel.GetTokenSerial(request);
        }
        
        public System.Threading.Tasks.Task<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoResponse> GetTokenSerialAsync(FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthService.SerialNoRequest request) {
            return base.Channel.GetTokenSerialAsync(request);
        }
    }
}
