//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthSoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TwoFactorAuthSoapService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResponseOnly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ResponseOnly(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResponseOnly", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ResponseOnlyAsync(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResponseOnlyForGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ResponseOnlyForGroup(string UserName, string Password, string GroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ResponseOnlyForGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ResponseOnlyForGroupAsync(string UserName, string Password, string GroupName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthSoapService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthSoapService.ServiceSoap>, FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthSoapService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ResponseOnly(string UserName, string Password) {
            return base.Channel.ResponseOnly(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<string> ResponseOnlyAsync(string UserName, string Password) {
            return base.Channel.ResponseOnlyAsync(UserName, Password);
        }
        
        public string ResponseOnlyForGroup(string UserName, string Password, string GroupName) {
            return base.Channel.ResponseOnlyForGroup(UserName, Password, GroupName);
        }
        
        public System.Threading.Tasks.Task<string> ResponseOnlyForGroupAsync(string UserName, string Password, string GroupName) {
            return base.Channel.ResponseOnlyForGroupAsync(UserName, Password, GroupName);
        }
    }
}
