using FintrakBanking.Entities.DocumentModels;
using FintrakBanking.Entities.Models;
using FintrakBanking.Entities.StagingModels;
using FintrakBanking.Interfaces;
using FintrakBanking.Interfaces.Admin;
using FintrakBanking.Interfaces.AlertMonitoring;
using FintrakBanking.Interfaces.AppEmail;
using FintrakBanking.Interfaces.CASA;
using FintrakBanking.Interfaces.credit;
using FintrakBanking.Interfaces.Credit;
using FintrakBanking.Interfaces.CreditLimitValidations;
using FintrakBanking.Interfaces.CRMS;
using FintrakBanking.Interfaces.Customer;
using FintrakBanking.Interfaces.ErrorLogger;
using FintrakBanking.Interfaces.Finance;
using FintrakBanking.Interfaces.Helper;
using FintrakBanking.Interfaces.media;
using FintrakBanking.Interfaces.Media;
using FintrakBanking.Interfaces.Notification;
using FintrakBanking.Interfaces.Reports;
using FintrakBanking.Interfaces.Risk;
using FintrakBanking.Interfaces.Setups;
using FintrakBanking.Interfaces.Setups.Approval;
using FintrakBanking.Interfaces.Setups.Credit;
using FintrakBanking.Interfaces.Setups.Finance;
using FintrakBanking.Interfaces.Setups.General;
using FintrakBanking.Interfaces.Setups.Risk;
using FintrakBanking.Interfaces.ThridPartyIntegration;
using FintrakBanking.Interfaces.Validation;
using FintrakBanking.Interfaces.WorkFlow;
using FintrakBanking.ReportObjects.ReportCalls;
using FintrakBanking.Repositories;
using FintrakBanking.Repositories.Admin;
using FintrakBanking.Repositories.AlertMonitoring;
using FintrakBanking.Repositories.AppEmail;
using FintrakBanking.Repositories.CASA;
using FintrakBanking.Repositories.credit;
using FintrakBanking.Repositories.Credit;
using FintrakBanking.Repositories.CreditLimitValidations;
using FintrakBanking.Repositories.CRMS;
using FintrakBanking.Repositories.Customer;
using FintrakBanking.Repositories.ErrorLogger;
using FintrakBanking.Repositories.Finance;
using FintrakBanking.Repositories.Helper;
using FintrakBanking.Repositories.media;
using FintrakBanking.Repositories.Media;
using FintrakBanking.Repositories.Notification;
using FintrakBanking.Repositories.Reports;
using FintrakBanking.Repositories.Risk;
using FintrakBanking.Repositories.Setups.Approval;
using FintrakBanking.Repositories.Setups.Credit;
using FintrakBanking.Repositories.Setups.Finance;
using FintrakBanking.Repositories.Setups.General;
using FintrakBanking.Repositories.Setups.Risk;
using FintrakBanking.Repositories.ThirdPartyIntegration;
using FintrakBanking.Repositories.Validetion;
using FintrakBanking.Repositories.WorkFlow;
using FinTrakBanking.ThirdPartyIntegration;
using FinTrakBanking.ThirdPartyIntegration.StagingDatabase.Finacle;
using FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthIntegration;
using Ninject.Modules;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthIntegration.TwoFactorAuthIntegrationService;

namespace FintrakBanking.MonitoringMessageLogger
{
    public class NinjectBinding : NinjectModule
    {
        public override void Load()
        {
            Bind<FinTrakBankingContext>().To<FinTrakBankingContext>();
            Bind<FinTrakBankingDocumentsContext>().To<FinTrakBankingDocumentsContext>();
            Bind<FinTrakBankingStagingContext>().To<FinTrakBankingStagingContext>();
            Bind<IBulkDisbursementPackageRepository>().To<BulkDisbursementPackageRepository>();
            Bind<IGeneralSetupRepository>().To<GeneralSetupRepository>();
            Bind<ICashBackRepository>().To<CashBackRepository>();
            Bind<IExternalAlertRepository>().To<ExternalAlertRepository>();
            Bind<IAuthenticationRepository>().To<AuthenticationRepository>();
            Bind<IAuthorizationRepository>().To<AuthorizationRepository>();
            Bind<IChartOfAccountRepository>().To<ChartOfAccountRepository>();
            Bind<IAccountCategoryRepository>().To<AccountCategoryRepository>();
            Bind<IAccountTypeRepository>().To<AccountTypeRepository>();
            Bind<ICompanyRepository>().To<CompanyRepository>();
            Bind<IBranchRepository>().To<BranchRepository>();
            Bind<ICurrencyRateRepository>().To<CurrencyRateRepository>();
            Bind<IRiskSetupRepository>().To<RiskSetupRepository>();
            Bind<IRiskImplementation>().To<RiskImplementation>();
            Bind<IStaffRepository>().To<StaffRepository>();
            Bind<IDepartmentRepository>().To<DepartmentRepository>();
            Bind<IMisInfoRepository>().To<MisInfoRepository>();
            Bind<ICollateralTypeRepository>().To<CollateralTypeRepository>();
            Bind<IAccountSensitivityRepository>().To<AccountSensitivityRepository>();
            Bind<IProductRepository>().To<ProductRepository>();
            Bind<IJobTitleRepository>().To<JobTitleRepository>();
            Bind<IStaffRoleRepository>().To<StaffRoleRepository>();
            Bind<IProductCollateralTypeRepository>().To<ProductCollateralTypeRepository>();
            Bind<IProductFeeRepository>().To<ProductFeeRepository>();
            Bind<ICustomerRepository>().To<CustomerRepository>();
            Bind<ICustomerProductFeeRepository>().To<CustomerProductFeeRepository>();
            Bind<ICustomerGroupRepository>().To<CustomerGroupRepository>();
            Bind<IAuditTrailRepository>().To<AuditTrailRepository>();
            Bind<ICultureHelper>().To<CultureHelper>();
            Bind<ICasaRepository>().To<CasaRepository>();
            Bind<IErrorLogRepository>().To<ErrorLogRepository>();
            Bind<IEmailRepository>().To<EmailRepository>();
            Bind<IAdminRepository>().To<AdminRepository>();
            Bind<ILoanCovenantRepository>().To<LoanCovenantRepository>();
            Bind<ICountryRepository>().To<CountryRepository>();
            Bind<ICustomerFSCaptionGroupRepository>().To<CustomerFSCaptionGroupRepository>();
            Bind<ICustomerFSCaptionRepository>().To<CustomerFSCaptionRepository>();
            Bind<ICustomerFSCaptionDetailRepository>().To<CustomerFSCaptionDetailRepository>();
            Bind<ICustomFieldsRepository>().To<CustomFieldsRepository>();
            Bind<ICustomerFSRatioRepository>().To<CustomerFSRatioRepository>();
            Bind<IChecklistRepository>().To<ChecklistRepository>();
            Bind<ILoanRepository>().To<LoanRepository>();
            Bind<IApprovalGroupMappingRepository>().To<ApprovalGroupMappingRepository>();
            Bind<IWorkflow>().To<Workflow>();
            Bind<IApprovalGroupRepository>().To<ApprovalGroupRepository>();
            Bind<IApprovalLevelRepository>().To<ApprovalLevelRepository>();
            Bind<IApprovalLevelStaffRepository>().To<ApprovalLevelStaffRepository>();
            Bind<ILoanApplicationRepository>().To<LoanApplicationRepository>();
            Bind<IMediaRepository>().To<MediaRepository>();
            Bind<ICanAuthorizationRepository>().To<CanAuthorizationRepository>();
            Bind<INotificationRepository>().To<NotificationRepository>();
            Bind<ITaxRepository>().To<TaxRepository>();
            Bind<IChargeFeeRepository>().To<ChargeFeeRepository>();
            Bind<ILoanScheduleRepository>().To<LoanScheduleRepository>();
            Bind<IAppraisalMemorandumRepository>().To<AppraisalMemorandumRepository>();
            Bind<ICreditTemplateRepository>().To<CreditTemplateRepository>();
            Bind<ILoanDocumentRepository>().To<LoanDocumentRepository>();
            Bind<ICollateralDocumentRepository>().To<CollateralDocumentRepository>();
            Bind<IJobRequestRepository>().To<JobRequestRepository>();
            Bind<ILoanPreliminaryEvaluationRepository>().To<LoanPreliminaryEvaluationRepository>();
            //Bind<ILimitRepository>().To<LimitRepository>();
            Bind<IFinanceTransactionRepository>().To<FinanceTransactionRepository>();
            Bind<ILoanOperationsRepository>().To<LoanOperationsRepository>();
            Bind<ICreditLimitValidationsRepository>().To<CreditLimitValidationsRepository>();
            Bind<IPublicHolidayRepository>().To<PublicHolidayRepository>();
            Bind<IAccreditedConsultantsRepository>().To<AccreditedConsultantsRepository>();
            Bind<IReportRoutes>().To<ReportRoutes>();
            Bind<ICallMemoRepository>().To<CallMemoRepository>();
            Bind<IConditionPrecedentRepository>().To<ConditionPrecedentRepository>();
            Bind<ITransactionDynamicsRepository>().To<TransactionDynamicsRepository>();
            Bind<IEmailAndAlertsRepository>().To<EmailAndAlertsRepository>();
            Bind<IEndOfDayRepository>().To<EndOfDayRepository>();
            Bind<IFinanceTransactionsReport>().To<FinanceTransactionsReport>();
            Bind<IKYCDocumentUploadRepository>().To<KYCDocumentUploadRepository>();
            Bind<IMonitoringSetupRepository>().To<MonitoringSetupRepository>();
            Bind<IOfferLetterAndAvailmentRepository>().To<OfferLetterAndAvailmentRepository>();
            Bind<ICustomerStagingRepository>().To<CustomerStagingRepository>();
            Bind<ILoanPrincipalRepository>().To<LoanPrincipalRepository>();
            Bind<ILoanMarketRepository>().To<LoanMarketRepository>();
            Bind<IPrudentialGuidelineSetupRepository>().To<PrudentialGuidelineSetupRepository>();
            Bind<ILoanRecoverySetupRepository>().To<LoanRecoverySetupRepository>();
            Bind<IEmployerRepository>().To<EmployerRepository>();
            Bind<ILoanReviewApplicationRepository>().To<LoanReviewApplicationRepository>();
            Bind<ICustomerCreditBureauRepository>().To<CustomerCreditBureauRepository>();
            Bind<IFeeConcessionRepository>().To<FeeConcessionRepository>();
            Bind<ILimitAndMonitoringRepository>().To<LimitAndMonitoringRepository>();
            Bind<IApprovalReliefRepository>().To<ApprovalReliefRepository>();
            Bind<ICasaLienRepository>().To<CasaLienRepository>();
            Bind<IContingentLoanUsageRepository>().To<ContingentLoanUsageRepository>();
            Bind<IOverRideRepository>().To<OverRideRepository>();
            Bind<IStaffAccountHistoryRepository>().To<StaffAccountHistoryRepository>();
            Bind<IIntegrationWithFinacle>().To<IntegrationWithFlexcube>();
            Bind<ILoanPerformanceRepository>().To<LoanPerformanceRepository>();
            Bind<IOverDraftValidation>().To<OverDraftValidation>();
            Bind<ICustomChartOfAccountRepository>().To<CustomChartOfAccountRepository>();
            Bind<IProfileSetupRepository>().To<ProfileSetupRepository>();
            Bind<IFXAccountCreationRepository>().To<FXAccountCreationRepository>();
            Bind<ILaonCamSolRepository>().To<LaonCamSolRepository>();
            Bind<ITwoFactorAuthIntegrationService>().To<TwoFactorAuthIntegrationService>();
            Bind<IStaffMIS>().To<StaffMIS>();
            Bind<IFacilityDetailSummary>().To<FacilityDetailSummary>();
            Bind<ICRMSRegulatories>().To<CRMSRegulatories>();
            Bind<IMemorandumRepository>().To<MemorandumRepository>();
            Bind<ICrmsRegulatoryRepository>().To<CrmsRegulatoryRepository>();
            Bind<IDashboardRepository>().To<DashboardRepository>();
            Bind<ICRMSCodeBookRepository>().To<CRMSCodeBookRepository>();
            Bind<IAPIErrorLog>().To<APIErrorLog>();
            //Bind<ApplicationOAuthProvider>().To<ApplicationOAuthProvider>();
            Bind<CreditCommonRepository>().To<CreditCommonRepository>();
            Bind<ILoanFeeChargeRepository>().To<LoanFeeChargeRepository>();

            Bind<IFinacleIntegrationRepository>().To<FinacleIntegrationRepository>();
            Bind<IEmailAlertLogger>().To<EmailAlertLogger>();
            Bind<IBusinessRuleRepository>().To<BusinessRuleRepository>();
            Bind<IDocumentUploadRepository>().To<DocumentUploadRepository>();
            Bind<IDocumentCategoryRepository>().To<DocumentCategoryRepository>();
            Bind<IDocumentCategoryTypeRepository>().To<DocumentCategoryTypeRepository>();
            Bind<IDocumentTypeRepository>().To<DocumentTypeRepository>();
            Bind<IDocumentUsageRepository>().To<DocumentUsageRepository>();
            Bind<IRiskAcceptanceCriteriaRepository>().To<RiskAcceptanceCriteriaRepository>();
            Bind<ITermSheetRepository>().To<TermSheetRepository>();
            Bind<ICreditOfficerRiskRepository>().To<CreditOfficerRiskRepository>();
            Bind<IOriginalDocumentApprovalRepository>().To<OriginalDocumentApprovalRepository>();
            Bind<ILcIssuanceRepository>().To<LcIssuanceRepository>();
            Bind<ILcDocumentRepository>().To<LcDocumentRepository>();
            Bind<ILcShippingRepository>().To<LcShippingRepository>();
            Bind<ILcConditionRepository>().To<LcConditionRepository>();
            Bind<ICustomerCollateralRepository>().To<CustomerCollateralRepository>();

            Bind<IAtcLodgmentRepository>().To<AtcLodgmentRepository>();
            Bind<IAtcLodgmentDetailRepository>().To<AtcLodgmentDetailRepository>();
            Bind<IProjectSiteReportRepository>().To<ProjectSiteReportRepository>();
            Bind<ILcUssanceRepository>().To<LcUssanceRepository>();
            Bind<ILetterGenerationRequestRepository>().To<LetterGenerationRequestRepository>();
            Bind<IValuationReportRepository>().To<ValuationReportRepository>();
            Bind<ICollateralValuationRepository>().To<CollateralValuationRepository>();
            Bind<IValuationRequestTypeRepository>().To<ValuationRequestTypeRepository>();
            Bind<IOriginalDocumentReleaseRepository>().To<OriginalDocumentReleaseRepository>();
            Bind<IRepaymentTermsRepository>().To<RepaymentTermsRepository>();
            Bind<IAuthourisedSignatoryRepository>().To<AuthourisedSignatoryRepository>();
            Bind<IAlertRepository>().To<AlertRepository>();
            Bind<ICashFlowLendingRepository>().To<CashFlowLendingRepository>();


        }
    }
}
