//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTrakBanking.ThirdPartyIntegration.CRCWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://crcnigeria.net/", ConfigurationName="CRCWebService.LiveRequestInvokerSoap")]
    public interface LiveRequestInvokerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crcnigeria.net/PostRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PostRequest(string strRequest, string strUserID, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://crcnigeria.net/PostRequest", ReplyAction="*")]
        System.IAsyncResult BeginPostRequest(string strRequest, string strUserID, string strPassword, System.AsyncCallback callback, object asyncState);
        
        string EndPostRequest(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LiveRequestInvokerSoapChannel : FinTrakBanking.ThirdPartyIntegration.CRCWebService.LiveRequestInvokerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PostRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiveRequestInvokerSoapClient : System.ServiceModel.ClientBase<FinTrakBanking.ThirdPartyIntegration.CRCWebService.LiveRequestInvokerSoap>, FinTrakBanking.ThirdPartyIntegration.CRCWebService.LiveRequestInvokerSoap {
        
        private BeginOperationDelegate onBeginPostRequestDelegate;
        
        private EndOperationDelegate onEndPostRequestDelegate;
        
        private System.Threading.SendOrPostCallback onPostRequestCompletedDelegate;
        
        public LiveRequestInvokerSoapClient() {
        }
        
        public LiveRequestInvokerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveRequestInvokerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveRequestInvokerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveRequestInvokerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<PostRequestCompletedEventArgs> PostRequestCompleted;
        
        public string PostRequest(string strRequest, string strUserID, string strPassword) {
            return base.Channel.PostRequest(strRequest, strUserID, strPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginPostRequest(string strRequest, string strUserID, string strPassword, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPostRequest(strRequest, strUserID, strPassword, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndPostRequest(System.IAsyncResult result) {
            return base.Channel.EndPostRequest(result);
        }
        
        private System.IAsyncResult OnBeginPostRequest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string strRequest = ((string)(inValues[0]));
            string strUserID = ((string)(inValues[1]));
            string strPassword = ((string)(inValues[2]));
            return this.BeginPostRequest(strRequest, strUserID, strPassword, callback, asyncState);
        }
        
        private object[] OnEndPostRequest(System.IAsyncResult result) {
            string retVal = this.EndPostRequest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPostRequestCompleted(object state) {
            if ((this.PostRequestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostRequestCompleted(this, new PostRequestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostRequestAsync(string strRequest, string strUserID, string strPassword) {
            this.PostRequestAsync(strRequest, strUserID, strPassword, null);
        }
        
        public void PostRequestAsync(string strRequest, string strUserID, string strPassword, object userState) {
            if ((this.onBeginPostRequestDelegate == null)) {
                this.onBeginPostRequestDelegate = new BeginOperationDelegate(this.OnBeginPostRequest);
            }
            if ((this.onEndPostRequestDelegate == null)) {
                this.onEndPostRequestDelegate = new EndOperationDelegate(this.OnEndPostRequest);
            }
            if ((this.onPostRequestCompletedDelegate == null)) {
                this.onPostRequestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostRequestCompleted);
            }
            base.InvokeAsync(this.onBeginPostRequestDelegate, new object[] {
                        strRequest,
                        strUserID,
                        strPassword}, this.onEndPostRequestDelegate, this.onPostRequestCompletedDelegate, userState);
        }
    }
}
