using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FintrakBanking.Repositories.Credit
{
   public class ExternalAlertRepository
    {
        // place holders
        private readonly string customerNameHolder = "@{{CustomerName}}";
        private readonly string branchNameHolder = "@{{Branch}}";
        private readonly string locationNameHolder = "@{{Location}}";
        private readonly string customerExposureHolder = "@{{CustomerExposure}}";
        private readonly string recommendedInterestRateHolder = "@{{RecommendedInterest}}";
        private readonly string isRelatedPartyHolder = "@{{IsRelatedParty}}";
        private readonly string dateCreatedHolder = "@{{DateCreated}}";
        private readonly string accountNumbersHolder = "@{{AccountNumbers}}";
        private readonly string approvalLevelHolder = "@{{ApprovalLevel}}";
        private readonly string environmentalSocialRiskHolder = "@{{EnvironmentalSocialRisk}}";
        private readonly string monitoringTriggersHolder = "@{{MonitoringTriggers}}";
        private readonly string proposedConditionsHolder = "@{{ProposedConditions}}";
        private readonly string conditionsPrecedenceListHolder = "@{{ConditionsPrecedenceList}}";
        private readonly string dynamicsListHolder = "@{{DynamicsList}}";
        private readonly string conditionsPrecedentToDrawdownHolder = "@{{ConditionsPrecedentToDrawdown}}";
        private readonly string transactionsDynamicsHolder = "@{{TransactionsDynamics}}";
        private readonly string isSecurityHolder = "@{{IsSecurity}}";
        private readonly string isOwnerOccupiedHolder = "@{{IsOwnerOccupied}}";
        private readonly string rmCountryHolder = "@{{Country}}";
        private readonly string misCodeHolder = "@{{MisCode}}";
        private readonly string reviewTypeHolder = "@{{ReviewType}}";
        private readonly string preparedByHolder = "@{{PreparedBy}}";
        private readonly string businessSectorsHolder = "@{{BusinessSectors}}";
        private readonly string exchangeRateHolder = "@{{ExchangeRate}}";
        private readonly string groupFacilitySummaryHolder = "@{{GroupFacilitySummary}}";
        private readonly string groupFacilitySummaryFcyHolder = "@{{GroupFacilitySummaryFcy}}";
        private readonly string directFacilitiesHolder = "@{{DirectFacilities}}";
        private readonly string totalDirectsHolder = "@{{TotalDirects}}";
        private readonly string contingentFacilitiesHolder = "@{{ContingentFacilities}}";
        private readonly string totalContingentsHolder = "@{{TotalContingents}}";
        private readonly string importFinanceFacilitiesHolder = "@{{ImportFinanceFacilities}}";
        private readonly string totalImportFinanceFacilitiesHolder = "@{{TotalImportFinanceFacilities}}";
        private readonly string foreignDirectFacilitiesHolder = "@{{ForeignDirectFacilities}}";
        private readonly string totalForeignDirectsHolder = "@{{TotalForeignDirects}}";
        private readonly string foreignContingentFacilitiesHolder = "@{{ForeignContingentFacilities}}";
        private readonly string totalForeignContingentsHolder = "@{{TotalForeignContingents}}";
        private readonly string foreignImportFinanceFacilitiesHolder = "@{{ForeignImportFinanceFacilities}}";
        private readonly string totalForeignImportFinanceFacilitiesHolder = "@{{TotalForeignImportFinanceFacilities}}";
        private readonly string totalFacilitiesHolder = "@{{TotalFacilities}}";
        private readonly string groupExposureHolder = "@{{GroupExposure}}";
        private readonly string approvalsHolder = "@{{Approvals}}";
        private readonly string currentDateHolder = "@{{CurrentDate}}";
        private readonly string annualReviewDateHolder = "@{{AnnualReviewDate}}";
        private readonly string securityAnalysisHolder = "@{{SecurityAnalysis}}";
        private readonly string allCustomerCollateralRemarksHolder = "@{{AllCustomerCollateralRemarks}}";
        private readonly string collateralCoverageHolder = "@{{CollateralCoverage}}";
        private readonly string allCustomerFacilitiesHolder = "@{{AllCustomerFacilities}}";
        private readonly string securityTypeHolder = "@{{SecurityType}}";
        private readonly string securityDescriptionHolder = "@{{SecurityDescription}}";
        private readonly string securityFirstSellValueHolder = "@{{SecurityFirstSellValue}}";
        private readonly string securityLocationHolder = "@{{SecurityLocation}}";
        private readonly string securityOpenMarketValueHolder = "@{{SecurityOpenMarketValue}}";
        private readonly string securityPerfectionStatusHolder = "@{{SecurityPerfectionStatus}}";
        private readonly string securityValuationDateHolder = "@{{SecurityValuationDate}}";
        private readonly string shareHoldersHolder = "@{{ShareHolders}}";
        private readonly string signitoriesHolder = "@{{Signitories}}";
        private readonly string directorsHolder = "@{{Directors}}";
        private readonly string amountDisbursedHolder = "@{{AmountDisbursed}}";
        private readonly string amountPaidSoFarHolder = "@{{AmountPaidSoFar}}";
        private readonly string amountProposedHolder = "@{{AmountProposed}}";
        private readonly string customerTurnoverHolder = "@{{CustomerTurnover}}";
        private readonly string memoHolder = "@{{memoData}}";
        private readonly string facilityUpgradeSupportSchemeHolder = "@{{facilityUpgradeSupportSchemeData}}";
        private readonly string invoiceDiscountingDataHolder = "@{{invoiceDiscountingData}}";
        private readonly string cashCollaterizedDataHolder = "@{{cashCollaterizedData}}";
        private readonly string temporaryOverdraftHolder = "@{{temporaryOverdraftData}}";
        private readonly string staffCarLoansDataHolder = "@{{staffCarLoansData}}";
        private readonly string staffMortgageLoansDataHolder = "@{{staffMortgageLoansData}}";
        private readonly string staffPersonalLoansAGMDataHolder = "@{{staffPersonalLoansAGMData}}";
        private readonly string staffPersonalLoanDataHolder = "@{{staffPersonalLoanData}}";
        private readonly string documentatonDeferralWaiverDataHolder = "@{{documentatonDeferralWaiverData}}";
        
        // properties to have getter methods for interfacing
        private string customerName;
        private string branchName;
        private string locationName;
        private string customerExposure;
        private string recommendedInterestRate;
        private string isRelatedParty;
        private string dateCreated;
        private string accountNumbers;
        private string approvalLevel;
        private string environmentalSocialRisk;
        private string monitoringTriggers;
        private string proposedConditions;
        private string conditionsPrecedenceList;
        private string dynamicsList;
        private string conditionsPrecedentToDrawdown;
        private string transactionsDynamics;
        private string rmCountry;
        private string misCode;
        private string reviewType;
        private string preparedBy;
        private string relationshipOfficerName;
        private string relationshipManagerName;
        private string businessSectors;
        private string exchangeRate;
        private string groupFacilitySummary;
        private string groupFacilitySummaryFcy;
        private string directFacilities;
        private string totalDirectFacilities;
        private string contingentFacilities;
        private string totalContingentFacilities;
        private string importFinanceFacilities;
        private string totalImportFinanceFacilities;
        private string foreignDirectFacilities;
        private string totalForeignDirectFacilities;
        private string foreignContingentFacilities;
        private string totalForeignContingentFacilities;
        private string foreignImportFinanceFacilities;
        private string totalForeignImportFinanceFacilities;
        private string totalFacilities;
        private string groupExposure;
        private string approvals;
        private string currentDate;
        private string annualReviewDate;
        private string securityAnalysis;
        private string allCustomerCollateralRemarks;
        private string collateralCoverage;
        private string allCustomerFacilities;
        private string securityType;
        private string securityDescription;
        private string securityFirstSellValue;
        private string securityLocation;
        private string securityOpenMarketValue;
        private string securityPerfectionStatus;
        private string securityValuationDate;
        private string shareHolders;
        private string signitories;
        private string directors;
        private string isSecurity;
        private string isOwnerOccupied;
        private string amountDisbursed;
        private string amountPaidSoFar;
        private string amountProposed;
        private string customerTurnover;
        private string currentAccountNo;
        private string facilityType;
        private string drawdownAmount;
        private int tenor;
        private int? moratorium;
        private string principalRepayment;
        private string interestRepayment;
        private double interestRate;
        private string processingFee;
        private string managementFee;
        private string commitmentFee;
        private string otherFee;
        private string effectiveDate;
        //private string misCode;

        private string approvedAmount;
        private string amountUtilised;
        private string newRequest;
        private string requestType;
        private string inPlace1;
        private string perfected1;
        private string deferred1;
        private string inPlace2;
        private string perfected2;
        private string deferred2;
        private string inPlace3;
        private string perfected3;
        private string deferred3;
        private string inPlace4;
        private string perfected4;
        private string deferred4;
        private string inPlace5;
        private string perfected5;
        private string deferred5;
        private string inPlace6;
        private string perfected6;
        private string deferred6;
        private string inPlace7;
        private string perfected7;
        private string deferred7;
        private string relationshipOfficer;
        private string relationshipManager;
        private string riskManagement;
        private string legal;
        private string treasury;
        private string coo;
        private string crmInternational;
        private string othersInPlace1;
        private string othersPerfected1;
        private string othersDeferred1;
        private string othersInPlace2;
        private string othersPerfected2;
        private string othersDeferred2;
        private string othersInPlace3;
        private string othersPerfected3;
        private string othersDeferred3;
        private string othersInPlace4;
        private string othersPerfected4;
        private string othersDeferred4;
        private string othersInPlace5;
        private string othersPerfected5;
        private string othersDeferred5;
        private string othersInPlace6;
        private string othersPerfected6;
        private string othersDeferred6;
        private string othersInPlace7;
        private string othersPerfected7;
        private string othersDeferred7;

        public string Replace(string content) // placeholders replace
        {
            content = content.Replace(customerNameHolder, customerName);
            content = content.Replace(branchNameHolder, branchName);
            content = content.Replace(customerExposureHolder, customerExposure);
            content = content.Replace(recommendedInterestRateHolder, recommendedInterestRate);
            content = content.Replace(isRelatedPartyHolder, isRelatedParty);
            content = content.Replace(dateCreatedHolder, dateCreated);
            content = content.Replace(locationNameHolder, locationName);
            content = content.Replace(approvalLevelHolder, approvalLevel);
            content = content.Replace(accountNumbersHolder, accountNumbers);
            content = content.Replace(proposedConditionsHolder, proposedConditions);
            content = content.Replace(conditionsPrecedenceListHolder, conditionsPrecedenceList);
            content = content.Replace(dynamicsListHolder, dynamicsList);
            content = content.Replace(conditionsPrecedentToDrawdownHolder, conditionsPrecedentToDrawdown);
            content = content.Replace(transactionsDynamicsHolder, transactionsDynamics);
            content = content.Replace(monitoringTriggersHolder, monitoringTriggers);
            content = content.Replace(environmentalSocialRiskHolder, environmentalSocialRisk);
            //content = content.Replace(environmentalAndSocialSummaryHolder, environmentalAndSocialSummary);
            content = content.Replace(rmCountryHolder, rmCountry);
            content = content.Replace(misCodeHolder, misCode);
            content = content.Replace(reviewTypeHolder, reviewType);
            content = content.Replace(preparedByHolder, preparedBy);
            content = content.Replace(businessSectorsHolder, businessSectors);
            content = content.Replace(exchangeRateHolder, exchangeRate);
            content = content.Replace(groupFacilitySummaryHolder, groupFacilitySummary);
            //content = content.Replace(groupFacilitySummaryFcyHolder, groupFacilitySummaryFcy);
            //content = content.Replace(directFacilitiesHolder, directFacilities);
            //content = content.Replace(totalDirectsHolder, totalDirectFacilities);
            //content = content.Replace(contingentFacilitiesHolder, contingentFacilities);
            //content = content.Replace(totalContingentsHolder, totalContingentFacilities);
            //content = content.Replace(importFinanceFacilitiesHolder, importFinanceFacilities);
            //content = content.Replace(totalImportFinanceFacilitiesHolder, totalImportFinanceFacilities);
            //content = content.Replace(foreignDirectFacilitiesHolder, foreignDirectFacilities);
            //content = content.Replace(totalForeignDirectsHolder, totalForeignDirectFacilities);
            //content = content.Replace(foreignContingentFacilitiesHolder, foreignContingentFacilities);
            //content = content.Replace(totalForeignContingentsHolder, totalForeignContingentFacilities);
            //content = content.Replace(foreignImportFinanceFacilitiesHolder, foreignImportFinanceFacilities);
            //content = content.Replace(totalForeignImportFinanceFacilitiesHolder, totalForeignImportFinanceFacilities);
            //content = content.Replace(totalFacilitiesHolder, totalFacilities);
            content = content.Replace(groupExposureHolder, groupExposure);
            content = content.Replace(approvalsHolder, approvals);
            content = content.Replace(currentDateHolder, currentDate);
            content = content.Replace(annualReviewDateHolder, annualReviewDate);
            content = content.Replace(securityAnalysisHolder, securityAnalysis);
            content = content.Replace(allCustomerCollateralRemarksHolder, allCustomerCollateralRemarks);
            content = content.Replace(collateralCoverageHolder, collateralCoverage);
            content = content.Replace(allCustomerFacilitiesHolder, allCustomerFacilities);
            //content = content.Replace(totalGroupExposureHolder, totalGroupExposure);

            //if (content.Contains(customerTurnoverHolder))
            //{
            //    customerTurnover = CustomerTurnoverMarkup();
            //    content = content.Replace(customerTurnoverHolder, customerTurnover);
            //}

            // lms cam only
            content = content.Replace(securityTypeHolder, securityType);
            content = content.Replace(securityDescriptionHolder, securityDescription);
            content = content.Replace(securityFirstSellValueHolder, securityFirstSellValue);
            content = content.Replace(securityLocationHolder, securityLocation);
            content = content.Replace(securityOpenMarketValueHolder, securityOpenMarketValue);
            content = content.Replace(securityPerfectionStatusHolder, securityPerfectionStatus);
            content = content.Replace(securityValuationDateHolder, securityValuationDate);
            content = content.Replace(shareHoldersHolder, shareHolders);
            content = content.Replace(signitoriesHolder, signitories);
            content = content.Replace(directorsHolder, directors);
            content = content.Replace(isSecurityHolder, isSecurity);
            content = content.Replace(isOwnerOccupiedHolder, isOwnerOccupied);
            content = content.Replace(amountDisbursedHolder, amountDisbursed);
            content = content.Replace(amountPaidSoFarHolder, amountPaidSoFar);
            content = content.Replace(amountProposedHolder, amountProposed);

            // for output document          
            //content = content.Replace(memoHolder, memoData);
            //content = content.Replace(facilityUpgradeSupportSchemeHolder, facilityUpgradeSupportSchemeData);
            //content = content.Replace(invoiceDiscountingDataHolder, invoiceDiscountingData);
            //content = content.Replace(cashCollaterizedDataHolder, cashCollaterizedData);
            //content = content.Replace(staffCarLoansDataHolder, staffcarLoansData);
            //content = content.Replace(staffMortgageLoansDataHolder, staffMortgageLoansData);
            //content = content.Replace(staffPersonalLoansAGMDataHolder, staffPersonalLoansAGMData);
            //content = content.Replace(staffPersonalLoanDataHolder, staffPersonalLoanData);
            //content = content.Replace(temporaryOverdraftHolder, temporaryOverdraftData);
            //content = content.Replace(documentatonDeferralWaiverDataHolder, documentatonDeferralWaiverData);
            //content = content.Replace(OfferLetterForBondsAndGuaranteesDataHolder, OfferLetterForBondsAndGuaranteesData);


            return content;
        }
    }


}
