using System;

namespace FintrakBanking.Common.Enum
{
    public enum AuditTypeEnum
    {
        AccountApproved = 1,
        AccountCategoryAdded = 2,
        AccountTypeAdded = 3,
        AccountTypeUpdated = 4,
        AppraisalMemorandumAdded = 5,
        AppraisalMemorandumUpdated = 6,
        ApprovalGroupAdded = 7,
        ApprovalGroupDeleted = 8,
        ApprovalGroupMappingAdded = 9,
        ApprovalGroupMappingDeleted = 10,
        ApprovalGroupMappingUpdated = 11,
        ApprovalGroupUpdated = 12,
        ApprovalLevelAdded = 13,
        ApprovalLevelDeleted = 14,
        ApprovalLevelStaffAdded = 15,
        ApprovalLevelStaffDeleted = 16,
        ApprovalLevelStaffUpdated = 17,
        ApprovalLevelUpdated = 18,
        ApprovalStatusUpdated = 19,
        BranchAdded = 20,
        BranchDeleted = 21,
        BranchUpdated = 22,
        ChargeFeeAdded = 23,
        ChargeFeeDeleted = 24,
        ChargeFeeUpdated = 25,
        ChartOfAccountDeleted = 26,
        ChartOfAccountInitiated = 27,
        ChartOfAccountUpdated = 28,
        ChecklistItemAdded = 29,
        ChecklistItemDeleted = 30,
        ChecklistItemUpdated = 31,
        CollateralCategoryAdded = 32,
        CollateralCategoryDeleted = 33,
        CollateralCategoryUpdated = 34,
        CollateralTypeAdded = 35,
        CollateralTypeDeleted = 36,
        CollateralTypeUpdated = 37,
        CreateStaffInitiated = 38,
        CreditTemplateAdded = 39,
        CreditTemplateUpdated = 40,
        CurrencyRateAdded = 41,
        CurrencyRateUpdated = 42,
        CustomFieldAdd = 43,
        CustomFieldDatadAdd = 44,
        CustomFieldDataDelete = 45,
        CustomFieldDelete = 46,
        CustomFieldUpdate = 47,
        CustomerAdded = 48,
        CustomerAddressAdded = 49,
        CustomerAddressDeleted = 50,
        CustomerAddressUpdated = 51,
        CustomerDeleted = 52,
        CustomerFSCaptionAdded = 53,
        CustomerFSCaptionDeleted = 54,
        CustomerFSCaptionGroupAdded = 55,
        CustomerFSCaptionGroupUpdated = 56,
        CustomerFSCaptionUpdated = 57,
        CustomerFSRatioCaptionAdded = 58,
        CustomerFSRatioCaptionDeleted = 59,
        CustomerFSRatioCaptionUpdated = 60,
        CustomerFSRatioDetailAdded = 61,
        CustomerFSRatioDetailDeleted = 62,
        CustomerFSRatioDetailUpdated = 63,
        CustomerFSCaptionDetailAdded = 64,
        CustomerFSCaptionDetailDeleted = 65,
        CustomerFSCaptionDetailUpdated = 66,
        CustomerGroupAdded = 67,
        CustomerGroupApproved = 68,
        CustomerGroupDeleted = 69,
        CustomerGroupMappingAdded = 70,
        CustomerGroupMappingDeleted = 71,
        CustomerGroupMappingUpdated = 72,
        CustomerGroupUpdated = 73,
        CustomerUpdated = 74,
        FeeAdded = 75,
        FeeApproved = 76,
        FeeUpdated = 77,
        JobRequestAdded = 78,
        JobRequestUpdated = 79,
        JobTypeAdded = 80,
        JobTypeUpdated = 81,
        LienPlaced = 82,
        LienReleased = 195,
        LimitAdded = 83,
        LimitDeleted = 84,
        LimitDetailAdded = 85,
        LimitDetailDeleted = 86,
        LimitDetailUpdated = 87,
        LimitUpdated = 88,
        LoanApplication = 89,
        LoanChecklistAdded = 90,
        LoanChecklistDefinitionAdded = 91,
        LoanChecklistDefinitionDeleted = 92,
        LoanChecklistDefinitionUpdated = 93,
        LoanChecklistDeleted = 94,
        LoanChecklistUpdated = 95,
        LoanDocumentAdded = 96,
        LoanDocumentUpdated = 97,
        LoanPreliminaryEvaluationAdded = 98,
        LoanPreliminaryEvaluationUpdated = 99,
        LoanBookingAdded = 100,
        LoanCovenantDetailAdd = 101,
        LoanCovenantDetailDelete = 102,
        LoanCovenantDetailUpdate = 103,
        LoanCovenantTypeAdd = 104,
        LoanCovenantTypeDelete = 105,
        LoanCovenantTypeUpdate = 106,
        LoggedOut = 107,
        LoggedIn = 108,
        ProductAdded = 109,
        ProductCollateralAdded = 110,
        ProductCollateralDeleted = 111,
        ProductFeeAdded = 112,
        ProductFeeDeleted = 113,
        ProductFeeUpdated = 114,
        ProductGroupAdded = 115,
        ProductGroupDeleted = 116,
        ProductGroupUpdated = 117,
        ProductPriceIndexDeleted = 118,
        ProductPriceIndexUpdated = 119,
        ProductPriceIndexAdded = 120,
        ProductTypeAdded = 121,
        ProductTypeUpdated = 122,
        ProductUpdated = 123,
        RiskAssessmentIndexAdd = 124,
        RiskAssessmentIndexDelete = 125,
        RiskAssessmentIndexUpdate = 126,
        RiskAssessmentTitleAdd = 127,
        RiskAssessmentTitleDelete = 128,
        RiskAssessmentTitleUpdate = 129,
        StaffDeleted = 130,
        StaffUpdated = 131,
        StaffApproved = 132,
        TaxAdded = 133,
        TaxDeleted = 134,
        TaxUpdated = 135,
        UserApproved = 136,
        UserUpdated = 137,
        UserAdded = 138,
        UserGroupAdded = 139,
        UserGroupUpdated = 140,
        LoanBookingApproved = 141,
        DepartmentAdded = 142,
        DepartmentUpdated = 143,
        PublicHolidayAdded = 144,
        PublicHolidayUpdated = 145,
        CollateralDocumentAdded = 155,
        CollateralDocumentUpdated = 156,
        LoanDailyInterestAccrual = 148,
        LoanDailyPrincipalAccrual = 148,
        CollateralValuerAdded = 149,
        ConditionPrecedentAdded = 150,
        ConditionPrecedentUpdated = 151,
        CollateralReleaseAction = 152,
        CollateralReleaseApproval = 153,
        RanEndOfDay = 150,
        KYCItemAdded = 151,
        KYCItemUpdated = 152,
        BulkRateLoanExcemption = 154,
        CollateralAssignmentAction = 157,
        CustomerGroupFSCaptionDetailAdded = 158,
        CustomerGroupFSCaptionDetailUpdated = 159,
        CustomerGroupFSCaptionDetailDeleted = 160,
        StaffSignatureUploaded = 161,
        StaffSignatureUpdated = 162,
        StateUpdated = 163,
        DepartmentUnitAdded = 164,
        DepartmentUnitUpdated = 165,
        DepartmentUnitDeleted = 166,
        MonitoringSetupAdded = 167,
        MonitoringSetupUpdated = 168,
        MonitoringSetupDeleted = 169,
        ForwardAppraisalMemorandum = 170,
        LoanPrincipalInserted = 171,
        LoanPrincipalUpdated = 172,
        LoanPrincipalDeleted = 173,
        LoanPrincipalEdited = 174,
        ApprovedMarketInserted = 175,
        ApprovedMarketUpdated = 176,
        ApprovedMarketDeleted = 177,
        ApprovedMarketEdited = 178,
        CustomerproductFeeAdded = 179,
        CustomerproductFeeUpdated = 180,
        CustomerproductFeeDeleted = 181,
        CustomerproductFeeApproved = 182,
        LoanApplicationUpdate = 183,
        LoanApplicationDelete = 184,

        SectorAdded = 183,
        SectorDeleted = 184,
        SectorUpdated = 185,

        LoanBookingRequested = 186,
        CollateralSearchJob = 187,
        CollateralChartJob = 188,
        MiddleOfficeVerification = 189,
        TransactionDynamicsAdded = 190,
        TransactionDynamicsUpdated = 191,
        ComplianceTimelineAdded = 192,
        ComplianceTimelineUpdated = 193,
        LoanRecoverySetupAdded = 186,
        LoanRecoverySetupUpdated = 187,
        LoanRecoverySetupDeleted = 188,
        LoanRecoveryPaymentPlanAdded = 189,
        LoanRecoveryPaymentPlanUpdated = 190,
        LoanRecoveryPaymentPlanDeleted = 191,
        CreditBureauReportDocumentAdded = 192,
        CreditBureauReportDocumentDeleted = 193,
        CreditBureauReportDocumentUpdated = 194,
        AlertAndMonitoryAdded = 195,
        AlertAndMonitoryUpdated = 196,
        StaffReliefAdded = 197,
        StaffReliefUpdated = 198,
        EndPendingSession = 197,

        ContingentLoanUsageAdd = 199,
        LoanBookingDisapproved = 200,
        CollateralSearchJobUpdate = 201,
        LoanPerformanceChange = 202,
        AddCommercialLoanBooking = 203,
        InitiatAccountReassigning = 204,
        LoanTenorExtended = 205,
        LoanInterestRateChange = 206,
        Loggedfailed = 207,
        WriteToStagingTable = 208,
        CustomChartOfAccountAdded = 208,
        CustomChartOfAccountUpdated = 209,
        CustomChartOfAccountDeleted = 210,
        CompanyDirectorAddedUpdated = 211,
        CompanyDirectorDeleted = 212,
        CustomerRelatedPartyAddedUpdated = 213,
        //BulkIntegrationPosting = 214,
        ConditionPrecedentDeleted = 215,
        BulkIntegrationPosting = 216,

        OverrideRequest = 214,
        ApprovedOverrideRequest = 217,
        AttemptedApproveOverrideRequest = 218,
        ForeignAccountCreation = 219,
        ForeignExchangeLoanAdded = 220,
        //new by adeyemi to be added to databases
        ProfileSettingsUpdated = 221,
        DocumentTemplateAdded = 222,
        DocumentTemplateUpdated = 223,
        DocumentTemplateSectionAdded = 224,
        DocumentTemplateSectionUpdated = 225,
        DocumentTemplateSectionDeleted = 226,
        DocumentTemplateSectionRoleAdded = 227,
        DocumentTemplateSectionRoleUpdated = 228,
        DocumentTemplateSectionRoleDeleted = 229,
        LoanRolledOver = 230,
        GroupLoanSubAllocated = 231,
        LoanPrePaid = 232,
        LoanApplicationCancellation = 242,

        CrmsRegulatorySetupAdded = 233,
        CrmsRegulatorySetupUpdated = 234,
        CrmsRegulatorySetupDeleted = 235,
        ApprovalReliefApproved = 243,
        CamsolApproval = 244,
        RegionDeleted = 245,
        ContingentLiabilityRenewal = 253,
        ContingentLiabilityTermination = 246,
        facilityBookingReferedBack = 247,
        lineAmountChange = 248,
        maturityInstruction = 249,
        LoginFailed = 250,
        ContingentLiabilityAmountReduction = 251,
        ContingentLiabilityTenorExtension = 252,
        StaffJobTypeAdded = 254,
        StaffJobTypeUpdated = 255,
        StaffJobTypeDeleted = 256,
        JobRequestHubStaffAdded = 257,
        JobRequestHubStaffUpdate = 258,
        JobRequestHubStaffDeleted = 259,
        LoanChargeFee = 260,
        ProductPriceIndexGlobalAdded = 261,
        ProductPriceIndexGlobalUpdated = 262,
        EditOfferLetterContent = 266,
        ContingentLiabilityRebook = 263,
        CollateralDocumentType = 264,
        CancelContingentLiability = 265,
        ContingentLiabilityAmountAddition = 267,
        LoanConsultantAdded = 268,
        LoanConsultantUpdated = 269,
        LoanDailyWriteoffInterestAccrual = 270,
        BusinessRuleAdded = 271,
        BusinessRuleUpdated = 272,
        BusinessRuleDeleted = 273,
        //new by Ifeanyi
        TermSheetAdded = 274,
        TermSheetUpdated = 275,
        TermSheetDeleted = 276,
        DocumentUploadAdded = 277,
        DocumentUploadDeleted = 278,
        DocumentUploadUpdated = 279,
        DocumentUsageAdded = 280,
        DocumentUsageUpdated = 281,
        DocumentUsageDeleted = 282,
        DocumentCategoryAdded = 283,
        DocumentCategoryUpdated = 284,
        DocumentCategoryDeleted = 285,
        DocumentCategoryTypeAdded = 286,
        DocumentCategoryTypeUpdated = 287,
        DocumentCategoryTypeDeleted = 288,
        DocumentTypeAdded = 289,
        DocumentTypeUpdated = 290,
        DocumentTypeDeleted = 291,
        RacCategoryDeleted = 292,
        RacCategoryUpdated=293,
        RacCategoryAdded = 294,
        RacDefinitionAdded = 295,
        RacDefinitionUpdated = 296,
        RacDefinitionDeleted = 297,
        RacDetailAdded = 298,
        RacDetailUpdated = 299,
        RacDetailDeleted =300,
        RacInputTypeAdded = 301,
        RacInputTypeUpdated =302,
        RacInputTypeDeleted = 303,
        RacItemAdded =304,
        RacItemUpdated = 305,
        RacItemDeleted = 306,
        RacOptionAdded = 307,
        RacOptionUpdated = 308,
        RacOptionDeleted = 309,
        RacOptionItemAdded =400,
        RacOptionItemUpdated = 401,
        RacOptionItemDeleted = 402,
        OriginalDocumentApprovalAdded = 403,
        OriginalDocumentApprovalUpdated = 404,
        OriginalDocumentApprovalDeleted = 405,
        LcIssuanceAdded = 406,
        LcIssuanceUpdated = 407,
        LcIssuanceDeleted = 408,
        LcConditionAdded = 409,
        LcConditionUpdated = 410,
        LcConditionDeleted = 411,
        LcDocumentAdded = 412,
        LcDocumentUpdated = 413,
        LcDocumentDeleted = 414,
        LcShippingAdded = 415,
        LcShippingUpdated = 416,
        LcShippingDeleted = 417,

        AtcLodgmentAdded = 418,
        AtcLodgmentUpdated = 419,
        AtcLodgmentDeleted = 420,
        AtcLodgmentDetailAdded = 421,
        AtcLodgmentDetailUpdated = 422,
        AtcLodgmentDetailDeleted = 423,
        AtcReleaseAdded = 424,
        AtcReleaseDeleted = 425,
        ProjectSiteReportAdded = 426,
        ProjectSiteReportUpdated = 427,
        ProjectSiteReportDeleted = 428,
        PsrRecommendationAdded = 429,
        PsrRecommendationUpdated = 430,
        PsrRecommendationDeleted = 431,
        PsrPerformanceEvaluationAdded = 432,
        PsrPerformanceEvaluationUpdated = 433,
        PsrPerformanceEvaluationDeleted = 434,
        PsrObservationAdded = 435,
        PsrObservationUpdated = 436,
        PsrObservationDeleted = 437,
        PsrNextInspectionTaskAdded = 438,
        PsrNextInspectionTaskUpdated = 439,
        PsrNextInspectionTaskDeleted = 440,
        PsrCommentAdded = 441,
        PsrCommentUpdated = 442,
        PsrCommentDeleted = 443,
        AtcTypeAdded = 444,
        AtcTypeDeleted = 445,
        LetterGenerationRequestAdded = 446,
        LetterGenerationRequestUpdated = 447,
        LetterGenerationRequestDeleted = 448,
        CallateralValuationReportAdded = 449,
        CallateralValuationAdded = 450,
        ValuationPrerequisiteAdded = 451,
        ValuationPrerequisiteDeleted = 452,
        ESGCategoryAdded = 453,
        ESGCategoryUpdated = 454,
        ESGCategoryDeleted = 455,
        ESGSUBCategoryAdded = 456,
        ESGSUBCategoryUpdated = 457,
        ESGSUBCategoryDeleted = 458,
        LCReleaseAmountAdded = 459,
        LCReleaseAmountUpdated = 500,
        //new by Kingsley
        LoanApplicationFlowChangeAdded =501,
        LoanApplicationFlowChangeUpdated=502,
        LoanApplicationFlowChangeDeleted =503,
        RepaymentTermAdded = 504,
        RepaymentTermUpdated = 505,
        RepaymentTermDeleted = 506,
        // Benjamin
        BulkDisbursementPackageAdded = 507,
        //end
        ValuationPrerequisiteUpdated = 508,
        BulkDisbursementPackageDeleted = 509,
        BulkDisbursementSchemeAdded = 510,
        BulkDisbursementSchemeUpdated = 511,
        BulkDisbursementSchemeDeleted = 512,
        BulkDisbursementFeesAdded = 513,
        BulkDisbursementFeesUpdated = 514,
        BulkDisbursementFeesDeleted = 515,
        BulkDisbursementPackageUpdated = 516,
        ProductDocumentMappingAdded = 517,
        DocumentDefinitionAdded = 518,

        //isaac
        CustomerContactAdded = 519,
        CustomerContactUpdated = 520,
        CustomerDetailAdded = 521,
        CustomerDetailUpdated = 522,
        PsrPerformanceAnalysisUpdated = 523,
        PsrPerformanceAnalysisAdded = 524,
        PsrPerformanceAnalysisDeleted = 525,
        AlertTitleAdded = 526,
        AlertTitleUpdated = 527,
        AlertTitleDeleted = 528,
        AlertSetupAdded = 529,
        AlertSetupUpdated = 530,
        AlertSetupDeleted = 531,
        AlertLevelGroupMappingAdded = 532,
        AlertLevelGroupMappingUpdated = 533,
        AlertLevelGroupMappingDeleted = 534,
        AlertLevelGroupAdded = 535,
        AlertLevelGroupUpdated = 536,
        AlertLevelGroupDeleted = 537,
        AlertLevelAdded = 538,
        AlertLevelUpdated = 539,
        AlertLevelDeleted = 540,
        AlertConditionAdded = 541,
        AlertConditionUpdated = 542,
        AlertConditionDeleted = 543,
        CashbackSectionAdded = 544,
        CashbackSectionUpdated = 545,
        LcUsanceAdded = 546,
        LcUsanceDeleted = 547,
        LcUsanceUpdated = 548,
        LienProposed = 549,
        LienUnproposed = 550,
        DocumentTemplatePrinted = 551,
        CrmsRecordAdded = 552,
        CustomerRelatedPartyDeleted = 553,
        CustomerPhoneContactDeleted = 554,
        CustomerContactAddressDeleted = 555,
        CustomerEmploymentHistoryDeleted = 556,

        // Ade
        CustomerFSCaptionGroupDeleted = 557,
        AlertGroupEmailAdded = 558,
        //lc lms


        CreateBulkPrepaymentReversal = 559,
        CreateBulkPrepayment = 560,

        LcEnhancementAdded = 559,
        LcEnhancementUpdated = 560,
        LcEnhancementDeleted = 561,
        CreditDocumentationPrinted = 562,
        ApplicationReassigned = 563,
        RemoveLien = 564,
        BulkLoanRecoveryAssignment = 565,
        BulkLoanRecoveryReport = 566,
        LcExtensionAdded = 567,
        LcExtensionUpdated = 568,
        LcExtensionDeleted = 569,
        LcCashBuildUpPlanAdded = 570,
        LcCashBuildUpPlanUpdated = 571,
        LcCashBuildUpPlanDeleted = 572,
        LcUsanceExtensionAdded = 573,
        LcUsanceExtensionUpdated = 574,
        WorkflowMappingNotificationsDeleted = 577,
        InsuranceBulkUpload = 578,
        FsCaptionBulkUpload = 579,
        LoanApplicationTagChange = 580,
        DigitalStampUpload = 581,
    }
    public enum RegulatoryTypeEnum
    {
        LoanType = 1,
        FeeType = 2,
        RepaymentAgreementType = 3,
        SecuredCollateralType = 4,
        UnsecuredCollateralType = 5,
        RepaymentSourceType = 6,
        LegalStatusType = 7,
        RelationshipType = 9,
        CompanySize = 10,
        FundingSource = 11,
    }
    public struct LicenseFileDetail
    {

        public LicenseStatus Status;

        public string Licensee;

        public DateTime LicenseDate;

        public DateTime ExpireDate;

        public string CoveredVersion;

        public string ServrMAC;

        public string Product;

        public string ServerMotherBoard;
    }
    public enum LicenseStatus
    {

        ValidLicense,

        MissingLicenseFile,

        CorruptLicenseFile,

        InvalidSignature,

        NotYetLicensed,

        LicenseExpired,

        VersionMismatch,
    }

    public static class General
    {
        public static DateTime DefaultDate = new DateTime(1900, 1, 1);
    }

}