public enum OperationsEnum
{
    //setup operations
    StaffCreation = 3,
    UserCreation = 4,
    ProductCreation = 5,
    ChartOfAccountCreation = 7,
    CustomerGroupCreation = 8,
    FeeCreation = 10,

    //loan origination operations

    TermLoanBooking = 1,
    LoanApplication = 2,
    CreditAppraisal = 6,
    LoanPreliminaryEvaluation = 9,
    CollateralSearchInitiation = 12,
    RevolvingLoanBooking = 13,
    ContigentLoanBooking = 14, 
    DailyInterestAccural = 15,
    InterestLoanRepayment = 16,
    LoanReversal = 17,
    LoanPrepayment = 18,
    ContractualInterestRateChange = 19,
    OverdraftSubAllocation = 20,
    Prepayment = 21,
    PrincipalFrequencyChange = 22,
    InterestFrequencyChange = 23,
    InterestandPrincipalFrequencyChange = 24,
    PaymentDateChange = 25,
    TenorChange = 26,
    CASAAccountChange = 27,
    OverdraftTopup = 28,
    Fee_chargeChange = 29,
    TerminateAndRebook = 30,
    CompleteWriteOff = 31,
    CancelUndisbursedLoan = 32,
    InterestSuspension = 33,
    LoanTermination = 34,
    CollateralRelease = 35,
    LoanBookingFeeDeferral = 36,
    OfferLetterApproval = 37, // MIGHT NOT BE USED
    LoanAvailment = 38,
    CorporateDrawdownRequest = 39,
    LoanBookingFeeOveride = 40,
    BondsAndGuarantees = OfferLetterApproval,
    DefferedChecklistApproval = 42,
    CustomerInformationApproval = 44,
    OverrideRequest = 43,
    LoanReviewApprovalApplication = 45,
    LoanReviewApprovalAppraisal = 46,
    LoanReviewApprovalOfferLetter = 47,
    LoanReviewApprovalAvailment = 48,
    FeeConcessionApproval = 49,
    CreditBureauSearch = 50,
    Restructured = 51,
    OverdraftTenorExtension = 52,
    OverdraftRenewal = 53,
    CollateralMaintenance = 54,
    StaffRoleCreation = 55,
    ContingentLiabilityUsage = 56,
    APSReleaseAPGApproval = 280,
    ReassigningOfAccount = 57,
    LoanSales = 58,
    LoanRecapitilization = 59,
    CollateralApproval = 60,
    IsurancePolicyApproval = 61,
    LoanPerformance = 62,
    CommercialLoanBooking = 63,
    LoanRecovery = 64,
    ChecklistOperation = 65,
    PrincipalLoanRepayment = 66,
    InterestPastDueLoanRepayment = 67,
    PrincipalPastDueLoanRepayment = 68,
    InterestOnPastDueInterest = 93,
    InterestOnPastDuePrincipal = 94,
    PenalFee = 69,
    CamsolBackbookModification = 70,
    NPLoanReviewApprovalAppraisal = 71,
    CommercialLoanRollOver = 72,
    ForeignExchangeLoanBooking = 73,
    CommercialLoanSubAllocation = 74,
    OverdraftInterestRate = 75,
    ApprovalWorkflowGroupModification = 76,
    ApprovalWorkflowLevelModification = 77,
    ApprovalLevelStaffModification = 78,
    LoanWorkOut = 80,
    LoanApplicationCancellation = 81,
    ContingentRequestBooking = 83,
    LoanAndOverdraftRequestBooking = 82,
    ContingentLiabilityTermination = 86,
    ContingentLiabilityRenewal = 85,
    FacilityLineAmountChange = 87,
    InterestRepricing = 89,
    //Added by Yemi
    StaffReliefCreation = 84,
    AccreditedConsultantCreated = 88,
    WrittenOffLoanReviewApprovalAppraisal = 79,
    CollateralSearchCompletion = 90,
    MaturityInstruction = 95,
    ContingentLiabilityTenorExtension = 96,
    ContingentLiabilityAmountReduction = 97,
    IndividualDrawdownRequest = 98,
    ManualFeeCharge = 99,
    GlobalInterestRateChange = 100,
    CustomerGroupMapping = 101,
    DeleteStaff = 102,
    UserAccountStatusChange = 103,
    ContingentLiabilityTerminateAndRebook = 104,
    CancelContingentLiability = 105,
    ContingentLiabilityAmountAddition = 106,
    APS_RelaseChecklist = 107,
    APS_ReleaseCAP = 108,
    APS_ReleasePrincipaRequest = 109,
    FinalCollateralRelease = 110,
    TemporalCollateralRelease = 111,
    DailyWriteoffInterestAccural = 112,
    LoanRecoveryPayment = 113,
    LoanRecoveryCompletion = 114,
    FullAndFinalCompleteWriteOff = 115,
    LmsOperations = 116,
    EarnUnEarnedFee = 117,
    CRMSApproval = 118,
    TenorExtensionApproval = 120,

    //
    LoanRecapitilizationApproval = 132,
    AdhocApproval = 133,
    OriginalDocumentApproval = 134,
    lcIssuance = 135,
    AtcReleaseApproval = 137,
    AtcLodgementApproval = 136,
    lcReleaseOfShippingDocuments = 138,
    ProjectSiteReportApproval = 139,
    lcUssance = 140,
    CreditCardDrawdownRequest = 141,
    RevolvingTranchDisbursement = 154,
    LetterGenerationRequest = 142,
    CollateralValuationRequest = 144,
    CreditCardsSalaryBacked = 145,
    CreditCardsCleanCards = 146,
    SecurityRelease = 147,
    WaivedChecklistApproval = 148,
    TemporaryOverdraftRequest = 149,
    //InitiationLevelAppraisal = 148,   //this has to be changed, using an existing enum
    CallMemo = 150,
    CashCollaterizedRequest = 153,
    //New Id's for existing Enumn that were edited
    AnnualReview = 200, //formerly id= 114
    IndictiveTermsheet = 201,   //formerly id = 115
    CreditCardsCashBacked = 202,    //formerly 116
    CollateralSwap = 206,
    FacilityModificationApproval = 207,

    OverdraftInterestRateChangeApproval = 211,
    ChangeRepaymentAccountApproval = 212,
    BulkLiquidationApproval = 216,
    RenewalApproval = 217,
    //PaymentDateChangeApproval = 218,
    //InterestAndPrincipalFrequencyChangeApproval = 219,
    //TenorExtensionApproval = 220,
    WriteoffApproval = 221,
    OverdraftRenewalApproval = 222,
    OverdraftTenorExtensionApproval = 223,
    OverdraftTopUpApproval = 224,
    OverdraftSubAllocationApproval = 225,
    APSReleaseApproval = 226,
    CancelContingentLiabilityApproval = 227,
    CancelInactiveContigentLiabilityApproval = 228,
    ContingentLiabilityAmountAdditionApproval = 229,
    ContingentLiabilityAmountReductionApproval = 230,
    ContingentTerminateApproval = 231,
    ContingentRebookApproval = 232,
    ContingentLiabilityTenorExtensionApproval = 233,
    ContingentLiabilityTerminationApproval = 234,
    ContingentLiabilityRenewalApproval = 235,
    ContingentLiabilityUsageApproval = 236,
    ExpiredContigentLiabilityApproval = 237,
    LCEnhancementApproval = 238,
    LCTerminationApproval = 239,
    GlobalInterestRateChangeApproval = 240,
    LoanReversalRepaymentApproval = 241,
    LoanReversalFeeApproval = 242,
    ManualFeeChargeCollectionApproval = 243,
    PrepaymentManualLiquidationApproval = 244,
    ReversalOfPrepaymentManualLiquidationApproval = 245,
    FacilityLineLimitChangeApproval = 246,
    FacilityLineTenorChangeApproval = 247,
    LoanRecoveryApproval = 248,

    ProvisionOfDeferredDocument = 259,
    DeferralExtension = 260,
    LienRemoval = 261,
    AssignRecoveryLoansToAgent = 264,
    UnAssignRecoveryLoansFromAgent = 281,
    RetailRecoveryAssignmentApproval = 283,
    UnAssignRetailRecoveryLoansFromAgent = 284,

    ReversalOfPrepayment = 249,
    BulkLiquidation = 258,
    
    RecoveryCommission = 269,
    RecoveryReporting = 124,
    LMSFacilityModificationApproval = 263,
    GuaranteeReleaseApproval = 270,

    RelatedEmployer = 273,
    LCIssuanceExtensionApproval = 274,
    ExceptionalLoan = 275,
    LCUsanceExtensionApproval = 276,
    LoanReviewDrawdownForExtension = 277,
    ContingentReviewDrawdownForExtension = 278,
    OverdraftReviewDrawdownForExtension = 279,
    LmsLoanApplicationCancellation = 285,
    InsuranceBulkUploadApproval = 286,
    IBLAvailmentInProgress = 287,
    StampDutyClosure = 288
}



public enum LCFundSource
{
    Cash = 1,
    IFF = 2
}