using FintrakBanking.Entities.DocumentModels;
using FintrakBanking.Entities.Models;
using FintrakBanking.Entities.StagingModels;
using FintrakBanking.Interfaces;
using FintrakBanking.Interfaces.Admin;
using FintrakBanking.Interfaces.AlertMonitoring;
using FintrakBanking.Interfaces.AppEmail;
using FintrakBanking.Interfaces.CASA;
using FintrakBanking.Interfaces.Credit;
using FintrakBanking.Interfaces.CreditLimitValidations;
using FintrakBanking.Interfaces.CRMS;
using FintrakBanking.Interfaces.Customer;
using FintrakBanking.Interfaces.ErrorLogger;
using FintrakBanking.Interfaces.Finance;
using FintrakBanking.Interfaces.Helper;
using FintrakBanking.Interfaces.media;
using FintrakBanking.Interfaces.Notification;
using FintrakBanking.Interfaces.Reports;
using FintrakBanking.Interfaces.Risk;
using FintrakBanking.Interfaces.Setups;
using FintrakBanking.Interfaces.Setups.Approval;
using FintrakBanking.Interfaces.Setups.Credit;
using FintrakBanking.Interfaces.Setups.Finance;
using FintrakBanking.Interfaces.Setups.General;
using FintrakBanking.Interfaces.Setups.Risk;
using FintrakBanking.Interfaces.ThridPartyIntegration;
using FintrakBanking.Interfaces.Validation;
using FintrakBanking.Interfaces.WorkFlow;
using FintrakBanking.Repositories;
using FintrakBanking.Repositories.Admin;
using FintrakBanking.Repositories.AlertMonitoring;
using FintrakBanking.Repositories.AppEmail;
using FintrakBanking.Repositories.CASA;
using FintrakBanking.Repositories.Credit;
using FintrakBanking.Repositories.CreditLimitValidations;
using FintrakBanking.Repositories.CRMS;
using FintrakBanking.Repositories.Customer;
using FintrakBanking.Repositories.ErrorLogger;
using FintrakBanking.Repositories.Finance;
using FintrakBanking.Repositories.Helper;
using FintrakBanking.Repositories.media;
using FintrakBanking.Repositories.Notification;
using FintrakBanking.Repositories.Reports;
using FintrakBanking.Repositories.Risk;
using FintrakBanking.Repositories.Setups.Approval;
using FintrakBanking.Repositories.Setups.Credit;
using FintrakBanking.Repositories.Setups.Finance;
using FintrakBanking.Repositories.Setups.General;
using FintrakBanking.Repositories.Setups.Risk;
using FintrakBanking.Repositories.ThirdPartyIntegration;
using FintrakBanking.Repositories.Validetion;
using FintrakBanking.Repositories.WorkFlow;
using FinTrakBanking.ThirdPartyIntegration;
using FinTrakBanking.ThirdPartyIntegration.StagingDatabase.Finacle;
using FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthIntegration;
using Hangfire;
using System;
using Unity;
using Unity.Lifetime;
using static FinTrakBanking.ThirdPartyIntegration.TwoFactorAuthIntegration.TwoFactorAuthIntegrationService;

namespace FintrakBanking.BackgroundTasksService.Container
{
    public class UnityJobActivator : JobActivator
    {
        private readonly IUnityContainer hangfireContainer;

        public UnityJobActivator(IUnityContainer hangfireContainer)
        {

             this.hangfireContainer.RegisterType<FinTrakBankingContext,FinTrakBankingContext>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<FinTrakBankingDocumentsContext,FinTrakBankingDocumentsContext>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<FinTrakBankingStagingContext,FinTrakBankingStagingContext>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IGeneralSetupRepository,GeneralSetupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAuthenticationRepository,AuthenticationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAuthorizationRepository,AuthorizationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IChartOfAccountRepository,ChartOfAccountRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAccountCategoryRepository,AccountCategoryRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAccountTypeRepository,AccountTypeRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICompanyRepository,CompanyRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IBranchRepository,BranchRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICurrencyRateRepository,CurrencyRateRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IRiskSetupRepository,RiskSetupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IRiskImplementation,RiskImplementation>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IStaffRepository,StaffRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IDepartmentRepository,DepartmentRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IMisInfoRepository,MisInfoRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICollateralTypeRepository,CollateralTypeRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAccountSensitivityRepository,AccountSensitivityRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IProductRepository,ProductRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IJobTitleRepository,JobTitleRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IStaffRoleRepository,StaffRoleRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IProductCollateralTypeRepository,ProductCollateralTypeRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IProductFeeRepository,ProductFeeRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerRepository,CustomerRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerProductFeeRepository,CustomerProductFeeRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerGroupRepository,CustomerGroupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAuditTrailRepository,AuditTrailRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICultureHelper,CultureHelper>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICasaRepository,CasaRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IErrorLogRepository,ErrorLogRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IEmailRepository,EmailRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAdminRepository,AdminRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanCovenantRepository,LoanCovenantRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerCollateralRepository,CustomerCollateralRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICountryRepository,CountryRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerFSCaptionGroupRepository,CustomerFSCaptionGroupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerFSCaptionRepository,CustomerFSCaptionRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerFSCaptionDetailRepository,CustomerFSCaptionDetailRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomFieldsRepository,CustomFieldsRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerFSRatioRepository,CustomerFSRatioRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IChecklistRepository,ChecklistRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanRepository,LoanRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IApprovalGroupMappingRepository,ApprovalGroupMappingRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IWorkflow,Workflow>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IApprovalGroupRepository,ApprovalGroupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IApprovalLevelRepository,ApprovalLevelRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IApprovalLevelStaffRepository,ApprovalLevelStaffRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanApplicationRepository,LoanApplicationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IMediaRepository,MediaRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICanAuthorizationRepository,CanAuthorizationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<INotificationRepository,NotificationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ITaxRepository,TaxRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IChargeFeeRepository,ChargeFeeRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanScheduleRepository,LoanScheduleRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAppraisalMemorandumRepository,AppraisalMemorandumRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICreditTemplateRepository,CreditTemplateRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanDocumentRepository,LoanDocumentRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICollateralDocumentRepository,CollateralDocumentRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IJobRequestRepository,JobRequestRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanPreliminaryEvaluationRepository,LoanPreliminaryEvaluationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IFinanceTransactionRepository,FinanceTransactionRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICreditLimitValidationsRepository,CreditLimitValidationsRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IPublicHolidayRepository,PublicHolidayRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAccreditedConsultantsRepository,AccreditedConsultantsRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICallMemoRepository,CallMemoRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IConditionPrecedentRepository,ConditionPrecedentRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ITransactionDynamicsRepository,TransactionDynamicsRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IEmailAndAlertsRepository,EmailAndAlertsRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IEndOfDayRepository,EndOfDayRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IFinanceTransactionsReport,FinanceTransactionsReport>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IKYCDocumentUploadRepository,KYCDocumentUploadRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IMonitoringSetupRepository,MonitoringSetupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IOfferLetterAndAvailmentRepository,OfferLetterAndAvailmentRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerStagingRepository,CustomerStagingRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanPrincipalRepository,LoanPrincipalRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanMarketRepository,LoanMarketRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IPrudentialGuidelineSetupRepository,PrudentialGuidelineSetupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanRecoverySetupRepository,LoanRecoverySetupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IEmployerRepository,EmployerRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanReviewApplicationRepository,LoanReviewApplicationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomerCreditBureauRepository,CustomerCreditBureauRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IFeeConcessionRepository,FeeConcessionRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILimitAndMonitoringRepository,LimitAndMonitoringRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IApprovalReliefRepository,ApprovalReliefRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICasaLienRepository,CasaLienRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IContingentLoanUsageRepository,ContingentLoanUsageRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IOverRideRepository,OverRideRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IStaffAccountHistoryRepository,StaffAccountHistoryRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IIntegrationWithFinacle,IntegrationWithFinacle>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanPerformanceRepository,LoanPerformanceRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IOverDraftValidation,OverDraftValidation>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICustomChartOfAccountRepository,CustomChartOfAccountRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IProfileSetupRepository,ProfileSetupRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IFXAccountCreationRepository,FXAccountCreationRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILaonCamSolRepository,LaonCamSolRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ITwoFactorAuthIntegrationService,TwoFactorAuthIntegrationService>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IStaffMIS,StaffMIS>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IFacilityDetailSummary,FacilityDetailSummary>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICRMSRegulatories,CRMSRegulatories>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IMemorandumRepository,MemorandumRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICrmsRegulatoryRepository,CrmsRegulatoryRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IDashboardRepository,DashboardRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ICRMSCodeBookRepository,CRMSCodeBookRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IAPIErrorLog,APIErrorLog>(new PerResolveLifetimeManager());
             //this.hangfireContainer.RegisterType<ApplicationOAuthProvider,ApplicationOAuthProvider>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<CreditCommonRepository,CreditCommonRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<ILoanFeeChargeRepository,LoanFeeChargeRepository>(new PerResolveLifetimeManager());
             this.hangfireContainer.RegisterType<IFinacleIntegrationRepository,FinacleIntegrationRepository>(new PerResolveLifetimeManager());
            this.hangfireContainer.RegisterType<IEmailAlertLogger,EmailAlertLogger>(new PerResolveLifetimeManager());
            this.hangfireContainer.RegisterType<ILoanOperationsRepository, LoanOperationsRepository>(new PerResolveLifetimeManager());

        }

        public override object ActivateJob(Type type)
        {
            return hangfireContainer.Resolve(type);
        }
    }
}