//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTrakBanking.ThirdPartyIntegration.CRCWebServiceNew {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://crcnigeria.net/", ConfigurationName="CRCWebServiceNew.LiveRequestInvokerSoap")]
    public interface LiveRequestInvokerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crcnigeria.net/PostRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PostRequest(string strRequest, string strUserID, string strPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://crcnigeria.net/PostRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> PostRequestAsync(string strRequest, string strUserID, string strPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LiveRequestInvokerSoapChannel : FinTrakBanking.ThirdPartyIntegration.CRCWebServiceNew.LiveRequestInvokerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LiveRequestInvokerSoapClient : System.ServiceModel.ClientBase<FinTrakBanking.ThirdPartyIntegration.CRCWebServiceNew.LiveRequestInvokerSoap>, FinTrakBanking.ThirdPartyIntegration.CRCWebServiceNew.LiveRequestInvokerSoap {
        
        public LiveRequestInvokerSoapClient() {
        }
        
        public LiveRequestInvokerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LiveRequestInvokerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveRequestInvokerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LiveRequestInvokerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PostRequest(string strRequest, string strUserID, string strPassword) {
            return base.Channel.PostRequest(strRequest, strUserID, strPassword);
        }
        
        public System.Threading.Tasks.Task<string> PostRequestAsync(string strRequest, string strUserID, string strPassword) {
            return base.Channel.PostRequestAsync(strRequest, strUserID, strPassword);
        }
    }
}
