using FintrakBanking.Entities.Models;
using FintrakBanking.ViewModels.Credit;
using FintrakBanking.ViewModels.Setups.General;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FintrakBanking.Interfaces.Credit
{
    public interface IExternalAlertRepository
    {
        string Decrypt(string cipher);
        void ValidateProfiledUsers(int maxUsers);
        IEnumerable<GlobalExposureApplicationViewModel> GetRecoveryAssignmentDueCompletionDate();
        bool QuarterlyAutoAssignRecoveryAnalysisByCustomer();
        bool MonthlyAutoAssignRecoveryAnalysisByCustomer();
        IEnumerable<RepaymentAlertViewModel> GetRepaymentPayDownAlert();
        IEnumerable<RepaymentAlertViewModel> GetRepaymentDefaultersAlert();
        IEnumerable<SectorLimitAlertViewModel> GetSectorLimitValidationBank();
        IEnumerable<SectorLimitAlertViewModel> GetSectorLimitValidationRBD();
        IEnumerable<SectorLimitAlertViewModel> GetSectorLimitValidationCIBD();
        IEnumerable<SectorLimitAlertViewModel> GetSectorLimitValidationCBD();
        IEnumerable<SectorLimitAlertViewModel> GetSectorLimitValidationBBD();
        IQueryable<LoanApplicationViewModel> GetPendingLoanApplications();
        List<LoanApplicationViewModel> CalculateSLA(List<LoanApplicationViewModel> apps);
        string GetSlaInduvidualStatus(LoanApplicationViewModel app);
        string GetSlaGlobalStatus(LoanApplicationViewModel app);
        string SlaStatus(float sla, int? elapse);
        IEnumerable<StaffInfoViewModel> GetPasDueObligationsAccountOfficersByGroupHeads(string groupHeadCode);
        IEnumerable<StaffInfoViewModel> GetDivisionalOfficersByGroupHeads(string groupHeadCode);
        IEnumerable<StaffInfoViewModel> GetAccountOfficersByGroupHeads(string groupHeadCode);
        IEnumerable<StaffInfoViewModel> GetImminentMaturitiesGroupHeads();
        IEnumerable<StaffInfoViewModel> GetAccountOfficersWithImminentMaturitiesCustomers();
        IEnumerable<StaffInfoViewModel> GetAccountOfficersWithImminentMaturities();
        IEnumerable<StaffInfoViewModel> GetAccountOfficersWithImminentDocumentMaturities();
        IEnumerable<StaffInfoViewModel> GetCreditCardDelinquencyMonitoringReport();
        IEnumerable<StaffInfoViewModel> GetOverlineMonitoringReport();
        IEnumerable<GlobalExposureViewModel> GetUnAuthorizedOverdraftReport();
        IEnumerable<GlobalExposureViewModel> GetLoanExpirationReminder();
        IEnumerable<StaffInfoViewModel> GetLoanExpirationReminderAccountOfficer();
        IEnumerable<StaffInfoViewModel> GetExpiringFacilityReport();
        IEnumerable<StaffInfoViewModel> GetCreditCardMaturingObligations();
        IEnumerable<StaffInfoViewModel> GetPastDueObligationsReminder();
        IEnumerable<StaffInfoViewModel> GetPastDueObligationsReminderByGroupHeads();
        IEnumerable<GlobalExposureViewModel> GetScheduleOfDirectorsAccounts();
        IEnumerable<GlobalExposureViewModel> GetLcUtilizationReportOne();
        IEnumerable<GlobalExposureViewModel> GetLcUtilizationReportTwo();
        IEnumerable<StaffInfoViewModel> GetNplOnCreditPortfolio();
        IEnumerable<StaffInfoViewModel> GetOverlineCreditCardPosition();
        bool GetRiskAssetsReportNotification();
        bool GetDashboardReportNotification();
        bool GetCACReport();
        IEnumerable<GlobalExposureViewModel> GetSignificantMovementInDailyRiskAsset();
        IEnumerable<GlobalExposureViewModel> GetUSDCreditCardReport();
        IEnumerable<GlobalExposureViewModel> GetNairaCreditCardReport();
        IEnumerable<GlobalExposureViewModel> GetCreditProgramsLimits();
        IEnumerable<GlobalExposureViewModel> GetSchemePerformanceReport();
        IEnumerable<AllCollateralViewModel> GetExpiredValuationReport();
        IEnumerable<GlobalExposureViewModel> GetExtentionReport();
        IEnumerable<GlobalExposureViewModel> GetCustomerStockTaking();
        IEnumerable<GlobalExposureViewModel> GetCustomerStockTakingReminder();
        IEnumerable<GlobalExposureViewModel> GetTranchPaymentReminder();
        IEnumerable<AllCollateralViewModel> GetValuationReminder();
        IEnumerable<GlobalExposureViewModel> GetInsuranceReminder();
        IEnumerable<GlobalExposureViewModel> GetExtendedFacilityNotification();
        IEnumerable<GlobalExposureViewModel> GetEnhancedDisbursementToDirectorsNotification();
        IEnumerable<TBL_LOAN_REVIEW_OPERATION> GetFacilityRestructuredNotification();
        IEnumerable<GlobalExposureViewModel> GetMccAndPpmcDeliverables();
        IEnumerable<GlobalExposureViewModel> GetMccAndPpmcDeliverablesReminder();
        IEnumerable<GlobalExposureViewModel> GetPastDueMccAndPpmcDeliverablesReminder();
        IEnumerable<GlobalExposureViewModel> GetDSRAReminder();
        IEnumerable<LoanApplicationViewModel> GetSLAReport();
        IEnumerable<GlobalExposureViewModel> GetOutstandingCreditDocumentation();
        IEnumerable<GlobalExposureViewModel> GetSiteVisitationCustomerReminder();
        IEnumerable<ChecklistApprovalViewModel> GetPastDueDeferredDocuments();
        IEnumerable<InsurancePolicy> GetExpiredInsurancePolicies();
        IEnumerable<GlobalExposureViewModel> GetAMCONCollectionAndStatusReport();
        IEnumerable<AllCollateralViewModel> GetSiteVisitationAccountReminder();
        IEnumerable<GlobalExposureViewModel> GetEAndSRiskCategorisationDashboard();
        IEnumerable<GlobalExposureViewModel> GetBankExposureEAndSExclusionListReport();
        IEnumerable<GlobalExposureViewModel> GetGreenBondProceedsUtilizationReport();
        IEnumerable<GlobalExposureViewModel> GetEandSConditionsPrecedentConfirmationReport();
        IEnumerable<GlobalExposureViewModel> GetEandSConditionsSubsequentMonitoringReport();
        IEnumerable<GlobalExposureViewModel> GetEandSCovenantDefaultReport();
        IEnumerable<GlobalExposureViewModel> GetInvoiceConfirmationReport();
        IEnumerable<GlobalExposureViewModel> GetStaockValuationReminder();
        IEnumerable<GlobalExposureViewModel> GetEndUseOfFundsReminder();
        IEnumerable<GlobalExposureViewModel> GetCollateralVerificationReminder();
        IEnumerable<GlobalExposureViewModel> GetCallMemoReminder();
        IEnumerable<DeferredChecklistViewModel> GetCreditFileChecklistReminder();
        IEnumerable<GlobalExposureViewModel> GetPendingCreditApprovalReport();
        IEnumerable<GlobalExposureViewModel> GetEmployerDeliquencyReport();
        IEnumerable<GlobalExposureViewModel> GetFacilitiesWithMissedPaymentReport();
        IEnumerable<GlobalExposureViewModel> GetRunoffs();
        IEnumerable<GlobalExposureViewModel> GetCashFlowMonitoringReport();
        IEnumerable<GlobalExposureViewModel> GetSalaryBackedLoans();
        IEnumerable<GlobalExposureViewModel> GetTODStatusReport();
        IEnumerable<GlobalExposureViewModel> GetCreditFileWithIncompleteDocumentationReport();
        IEnumerable<GlobalExposureViewModel> GetOutstandingCollateralDocumentation();
        IEnumerable<GlobalExposureViewModel> GetAccountDeferralReport();
        IEnumerable<GlobalExposureViewModel> GetContigentLiabilityReport();
        IEnumerable<GlobalExposureViewModel> GetProcessedTransactionReport();
        IEnumerable<GlobalExposureViewModel> GetPendingAndDeclinedTransactionReport();
        IEnumerable<GlobalExposureViewModel> GetLoanCovenantsReport();
        IEnumerable<GlobalExposureViewModel> GetVisitationAndSiteInspectionReport();
        IEnumerable<GlobalExposureViewModel> GetCollateralReleaseAndAccountDeclassification(); 
        IEnumerable<GlobalExposureViewModel> GetStockMonitoringReport();
        IEnumerable<GlobalExposureViewModel> GetDSRAReport();
        IEnumerable<GlobalExposureViewModel> GetPostDisbursementReview();
        IEnumerable<GlobalExposureViewModel> GetMeetUpMonthlyTurnoverRequrements();
        IEnumerable<GlobalExposureViewModel> GetMeetUpMonthlyTurnoverRequrementSMS();
        IEnumerable<GlobalExposureViewModel> GetBreachInCreditKeyMetricsNotification();
        IEnumerable<GlobalExposureViewModel> GetBreachInCreditKeyMetricsNotificationReminder();
        IEnumerable<GlobalExposureViewModel> GetAssignedDeliverableFromCACMeeting();
        IEnumerable<StaffInfoViewModel> GetExpiredFacilityNotification();
        IEnumerable<StaffInfoViewModel> GetLoanRepaymentReminderAccountOfficer();
        IEnumerable<GlobalExposureViewModel> GetLargeExposureAbove18PercentNotification();
        IEnumerable<GlobalExposureViewModel> GetBreachInGeographyLimitNotification();
        IEnumerable<GlobalExposureViewModel> GetBreachInORRLimitNotification();
        IEnumerable<GlobalExposureViewModel> GetBreachInSectorLimitNotification();
        IEnumerable<GlobalExposureViewModel> GetImminentObligationRentalScheduleNotification();
        IEnumerable<StaffInfoViewModel> GetImminentObligationMaturityFacilityNotification();
        IEnumerable<StaffInfoViewModel> GetOverlineFacilityNotification();
        IEnumerable<StaffInfoViewModel> GetPastDueFacilitiesNotification();
        IEnumerable<GlobalExposureViewModel> GetLoanRepaymentReminder();
        IEnumerable<StaffInfoViewModel> GetOverlineReminder();
        IEnumerable<StaffInfoViewModel> GetUnpaidObligationReminderAccountOfficer();
        IEnumerable<StaffInfoViewModel> GetMaturingObligationsReport();
        IEnumerable<GlobalExposureViewModel> GetLargeExposureMonitoring();
        IEnumerable<GlobalExposureViewModel> GetUnpaidObligationReminder();
        IEnumerable<StaffInfoViewModel> GetStaffLoanPortfolioReport();
        IEnumerable<GlobalExposureViewModel> GetExStaffLoanPortfolioReport();
        IEnumerable<GlobalExposureViewModel> GetImminentMaturitiesAlertEmail();
        IEnumerable<GlobalExposureViewModel> GetDelinquentCustomersAlertEmail();
        IEnumerable<GlobalExposureViewModel> GetDelinquentCustomersAlertSMS();
        IEnumerable<GlobalExposureViewModel> GetCoreExposureForOneYearPeriodNotification();
        IEnumerable<GlobalExposureViewModel> GetPotentialAndPipelineAssetToBeFinance();
        IEnumerable<GlobalExposureViewModel> GetCashBuildupReport();
        IEnumerable<GlobalExposureViewModel> GetCustomersWithNoInflows();
        IEnumerable<GlobalExposureViewModel> GetCustomersWithTurnoverLessthan100();
        
    }
}
